version: "1"

networks:
  node-api-network:
    name: node-api-network

services:
  express:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    depends_on:
      - mysql-server
    networks:
      - node-api-network
  mysql-server:
    image: mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - node-api-network
